import  PushNotification from 'react-native-push-notification'
import {
    Platform
} from 'react-native'

import moment from 'moment'
export  function nowNotification() {


    PushNotification.localNotification({
        /* Android Only Properties */
        id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        ticker: "My Notification Ticker", // (optional)
        autoCancel: true, // (optional) default: true
        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
        smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
        subText: "This is a subText", // (optional) default: none
        color: "red", // (optional) default: system default
        vibrate: true, // (optional) default: true
        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
        tag: 'some_tag', // (optional) add tag to message
        group: "group", // (optional) add group to message
        ongoing: false, // (optional) set whether this is an "ongoing" notification

        /* iOS only properties */
        //alertAction: '', // (optional) default: view
        //category: null, // (optional) default: null
        userInfo: {'type':'local'},// (optional) default: null (object containing additional notification data)

        /* iOS and Android properties */
        title: "My Notification Title", // (optional, for iOS this is only used
        // in apple watch, the title will be the app name on other iOS devices)
        message: "测试", // (required)
        // playSound: false, // (optional) default: true
        // soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
        number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
         repeatType: 'day', // (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval
        actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
    });
}
export async function  dayNotification() {

    PushNotification.cancelAllLocalNotifications()

    // let res = 0
    //   PushNotification.getApplicationIconBadgeNumber(item=>{
    //       res = item
    //       console.log('test:', '222');
    //   })

    //
    // const time =  moment(20, "HH").day(7).format('YYYY-MM-DD HH:mm:ss');
    //
    // console.log('moment:',  moment().toDate());
    // console.log('Date:',  new Date());

    PushNotification.localNotificationSchedule({
        message: "今天的挑战完成了吗？", // (required)
        date: moment(20, "HH").toDate(), // in 60 secs
        // date: new Date(Date.now() + (1*1000)), // in 60 secs
        number:  1,
        repeatType: 'day',
        userInfo: {'type': 'local'},
    });

    PushNotification.localNotificationSchedule({
        message: "设置一些本周挑战吧~！", // (required)
        date: moment(20, "HH").day(7).toDate(), // in 60 secs
        // date: new Date(Date.now() + (1*1000)), // in 60 secs
        number: 1,
        repeatType: 'week',
        userInfo: {'type': 'local'},
    });


}