# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'RNStartKit' do
    #定义dayibase的版本。
pod 'Reveal-iOS-SDK' ,:configurations => ['Debug']

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

end


